version: '3.8'

services:
  backend:
    build: ./backend
    container_name: financial-backend
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - ./backend/.env
    networks:
      - financial-network

  frontend:
    build: ./frontend
    container_name: financial-frontend
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:${STREAMLIT_SERVER_PORT:-8501}"
    env_file:
      - ./frontend/.env
    networks:
      - financial-network

networks:
  financial-network:
    driver: bridge
