[project]
name = "desafio-tecnico-ia-developer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn>=0.35.0",
    "pydantic-settings>=2.0.0",
]
